### ISSUE TITLE
microsoft edge disables the extension

### ISSUE THREAD

**Issue by grysor** [BernhardWebstudio/EdgeNewTab#1]
hello, thanks for this extension. But there is a problem:
Whenever I open Microsoft Edge, the browser automatically disables the extension! How to fix this problem? thank you in advance :)

**Comment by GenieTim** [comment]
Hi! Thanks for reaching out. 
The extension has to be [packaged](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/packaging/using-manifoldjs-to-package-extensions) and [signed](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/packaging/creating-and-testing-extension-packages#testing-an-appx-package) for it to be accepted as an 'official' app, which then would not be disabled automatically. I already spent a Sunday packaging the extension, it will take a few days until I find time again, then I will try to sign it and update this issue on success.

**Comment by grysor** [comment]
Hello, thank you for your answer and these explanations :)
I wish you good luck and thank you for your excellent work

**Comment by GenieTim** [comment]
I do have a packed extension now, instructions are added to the [README](https://github.com/BernhardWebstudio/EdgeNewTab#the-other-way). Still, although I was successful in installing it locally, it requires some additional changes in the registry (not documented yet as I could not settle on one) to keep it activated, as it is currently labelled as "from unknown source" which again leads to deactivation sometimes. At some point, I am not entirely sure if it s worth it, just to use Edge, not Firefox or Chrome with the corresponding "New Tab" resp. "Momentum" extensions.

**Comment by grysor** [comment]
Hello thank you for your message :) yes indeed i installed your new extension and indeed it is always disabled when i close edge and restart it ...
I wanted to try what you indicated in the tab "code" of your extension:
"TLDR:
Download / clone the repo.
Label the certificate as trusted: 2.1 Run Cmd.exe as administrator. 2.2 Run this command from the repo-directory:'Certutil -addStore TrustedPeople. \ Certificates \ MyKey.cer'
Install the app: 3.1. Run PowerShell as administrator 3.2. Run this command from the repo-directory: Add-AppxPackage. \ Package \ edgeExtension.appx' "

but I did not understand how to do this:
"2.2 Run this command from the repo-directory:'Certutil -addStore TrustedPeople. \ Certificates \ MyKey.cer'"

-The repo-directory is where? in cmd.exe? If yes i did it but it does not work :(

**Comment by GenieTim** [comment]
The Repo-Directory is where you put this whole Folder. Say, sou downloaded and extraced this Repo to the Downloads Folder, you first need to set the current directory of the Command-line therein, like this: `cd Downloads\EdgeNewTab`.

**Comment by grysor** [comment]
hello thank you for your help
I tried but the commands by cmd in administrator do not work ... I am novice too ... would it be possible that you post a video youtube or screenshots step by step? thank you in advance

**Comment by grysor** [comment]
this is what I can not do :(
"you first need to set the current directory of the Command-line therein, like this: cd Downloads\EdgeNewTab"
-I named the folder or I put inside the unzipped extension:  cd Downloads
-but that's not what I have to do, I think? :(

**Comment by GenieTim** [comment]
I will see if I find time for a video tutorial once.
But yeah, to switch into a directory (that means, just like you open a folder in Explorer, we have to open a folder in the command line) we use the command `cd` and append after a space the path and name of the folder we want to switch into. I would suggest, if you still want to try, you open the unzipped repository (say, after from the code tab, top right, clicking download as zip, then unpacking) in file explorer. You will have the path in the adress line. Click there, copy the path, go to console, type `cd `, right click into console and select paste. Press enter and you should have switched to the right directory.

**Comment by GenieTim** [comment]
Is the following comprehensive enough: [instruction video](https://github.com/BernhardWebstudio/EdgeNewTab/blob/master/readme-assets/installation-instructions.mp4) ?

**Comment by bolera** [comment]
I think you have to enable developer mode, it won't work any other way. An extension is the same as an UWP app and this is the only way how "non store" apps can be added.

**Comment by GenieTim** [comment]
Good point, thanks @bolera ! 
 
@grysor , may I mark this issue as resolved?

**Comment by grysor** [comment]
Hello BernhardWebstudio
I am sorry for my very long absence i apologize, i had some problems.
I thank you very much for your excellent video very well explained and for the time you took to make this video to explain myself :) 

I followed exactly and perfectly your video, but it gives me these errors each time :(  :
![sanstitre1](https://user-images.githubusercontent.com/35570935/51446460-ca2bdd80-1d12-11e9-9ff7-70bd4c46f391.jpg)

on my screenshot of cmd, it's written in french because i'm french

@bolera 
Hello
thank you for your answer and this precision
do you mean : developer mode in the windows settings? If yes i am in mode developer for at least 3 years

I do not know why cmd returns these mistakes :(

**Comment by GenieTim** [comment]
Well, the error message is clear: it does not find the specified path, I guess it means the certificate is not found. If you run `dir .\certificates\` from where you are, does `MyCert.cer` show up?
An alternative approach may be to just type `Certutil -addStore TrustedPeople ` (watch the space in the end) and drag and drop the MyCert.cer file (you should find it [here](https://github.com/BernhardWebstudio/EdgeNewTab/blob/master/certificates/MyKey.cer?raw=true) to download separately) to the end of this command, then press enter. This way, the path will automatically be resolved correctly, for whatever reason it does not do that now already.

**Comment by grysor** [comment]
Hi BernhardWebstudio, thank you for your help. I started all over again from the command prompt in admin and this time miracle it worked here is what it indicated me :
![999](https://user-images.githubusercontent.com/35570935/51508837-43046580-1df7-11e9-958f-56780dce696d.jpg)

but then, i continue to scrupulously follow your video help and after having validated : 
Add-AppxPackage .\package\edgeExtension.appx , i had this error in red color, but i found why: 
It was because there was a (1) after EdgeNewTab-master
![998](https://user-images.githubusercontent.com/35570935/51509589-fec69480-1df9-11e9-80c2-cade495e94dd.jpg)

so i deleted (1) by renaming. Then i tried again and as you can see it worked.
I had the dotted kinds as in your video that would confirm that it worked, but after closing the command prompt and powershell, i opened microsoft edge and nothing to do it does not work, edge always off your newtab extension :(  as you can see below  : 

![sans tit114re](https://user-images.githubusercontent.com/35570935/51509701-70064780-1dfa-11e9-89ca-f205ded8fa9d.png)

I then tried your last solution by typing:
dir. \ certificates \
and here's what it tells me:
![997](https://user-images.githubusercontent.com/35570935/51510149-27e82480-1dfc-11e9-9962-2263cd642901.jpg)

then i do not know what else to do because i'm novice :(
I tried your 2nd solution: drag and drop the file MyKey.cer just after Certutil -addStore TrustedPeople but the file does not want paste in the command prompt, i re-tried several times later validating but nothing to to do it is not paste :(

**Comment by GenieTim** [comment]
In theory, it looks like everything worked out, as I understand your outputs. 
I did not use the app myself as I switched to using Firefox, so I do not know if possibly one of the last Edge or Windows updates rendered the workaround worthless. Sigh.

Edit: You had more than one version downloaded, that is where the (1) came from. You ran the Certutil command from the newer download, the AddAppx from the elder. I am not sure if this is a problem? Also, make sure to run the Certutil before the AddAppx...
Also, when you open about:flags as URL in Edge, did you enable the Developer mode there too?

**Comment by grysor** [comment]
Hello
"Edit: You had more than one version downloaded, that is where the (1) came from."
-ah ok i understand. Yes it was for that.

" You ran the Certutil command from the newer download, the AddAppx from the elder. I am not sure if this is a problem?"
-for the knowledge, today i started all over again, i uninstalled the extension by clicking on "uninstall" all the bottom right as on my Screenshot :
![edge](https://user-images.githubusercontent.com/35570935/51696098-fb532900-2004-11e9-9d95-9d9c884dc131.png)


122/5000
then i re-installed it by clicking on "load an extension" in edge all the bottom right as on my Screenshot:
![edge2](https://user-images.githubusercontent.com/35570935/51696885-dbbd0000-2006-11e9-8b42-c7ddb73f2d1d.jpg)
and i selected the folder :  " C:\Users\**\Downloads\EdgeNewTab-master " 
It functioned :) 
then i redid everything with the command prompt by re-following your help video,here is the result:

![newtab](https://user-images.githubusercontent.com/35570935/51696283-6b61af00-2005-11e9-89d1-b5d222f10aaf.jpg)
and by powershell in admin then:
![appx](https://user-images.githubusercontent.com/35570935/51696375-a6fc7900-2005-11e9-84f1-e11d8453f65b.jpg)

unfortunately i restarted edge and i activated the extension, google appears well in new tab as usual, but when i close edge and restart it, edge disables the newtab extension ,i re-tried several times and nothing to do :(

for your last question:
"Also, when you open about:flags as URL in Edge, did you enable the Developer mode there too?"
-yes i have been in dev mode for a very long time :)  : 
![dev1](https://user-images.githubusercontent.com/35570935/51697741-dcef2c80-2008-11e9-9163-3d1d5a5a3168.png)
![dev2](https://user-images.githubusercontent.com/35570935/51697784-f6907400-2008-11e9-98dd-5629ff8ae9ed.png)

I think, as you tell me, that the last Edge or Windows updates rendered the workaround worthless :(
but i thank you for all your research, your huge work and maybe one day you will find a workaround ;) 
but perso it bothers me very little :) because like you i use a lot more firefox and chrome who have the new tab google by adding an extension :)

**Comment by GenieTim** [comment]
Alright, thanks for the comprehensive answer. I allow myself to close the issue in this case and archive this repo as it seems that there is no sense in keeping it alive. 

Passez du bon temps!
